#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# if DISPLAY is an empty string and the virtual terminal number is equal to one
if [[ -z "${DISPLAY}" ]] && [[ "$(tty)" = "/dev/tty1" ]]; then
	exec startx
fi
