#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
# Always color 'tree' output
alias tree='tree -C'
# Run vim as a root with ~/.vim/vimrc
alias sudovim='sudo vim -u ~/.vim/vimrc'
# Run google chrome
alias chrome='google-chrome-stable 2>/dev/null & disown'
# Run telegram
alias teleg='telegram-desktop 2>/dev/null & disown'
PS1='[\u@\h \W]\$ '

# BEGIN_KITTY_SHELL_INTEGRATION
if test -n "$KITTY_INSTALLATION_DIR" -a -e "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; then source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; fi
# END_KITTY_SHELL_INTEGRATION
