" DEFAULT ---------------------------------------------------------------- {{{

" }}}


" PLUGINS ---------------------------------------------------------------- {{{


" }}}


" MAPPINGS --------------------------------------------------------------- {{{


" }}}


" VIMSCRIPT -------------------------------------------------------------- {{{

" This will enable code folding.
" Use the marker method of folding.
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

" More Vimscripts code goes here.

" }}}


" STATUS LINE ------------------------------------------------------------ {{{

" Status bar code goes here.

" }}}

