" ==========  DEFAULT ==========

" Maximize window
set lines=300 columns=300
" Set default font-size
set guifont=14
" Remove the toolbar
set guioptions-=T


" ==========  PLUGINS ==========



" ==========  MAPPINGS ==========



" ==========  VIMSCRIPT ==========



" ==========  STATUS LINE ==========
