" ==========  DEFAULT ==========

" maximize window
set lines=999 columns=999
" set default font-size
set guifont=14


" ==========  PLUGINS ==========



" ==========  MAPPINGS ==========



" ==========  VIMSCRIPT ==========



" ==========  STATUS LINE ==========
