" ==========  DEFAULT ==========
"
" ===== not grouped =====
" Enable file type plugin
filetype plugin on
" Turn syntax highlighting on.
syntax on
" Show line numbers
set number
" Disable swap files
set noswapfile

" ===== searching =====
" Highlight all search pattern
set hlsearch
" Highlight all matches while entering patter
set incsearch
" Ignore case while searching
set ignorecase
" If at least 1 character Upper case, case-sensitive search
set smartcase



" ==========  PLUGINS ==========
"
" ===== vim-xkbswitch =====
" Basic configuration
let g:XkbSwitchEnabled=1
" Insert mappings duplicates for Ukrainian layout
let g:XkbSwitchIMappings=['uk']



" ==========  MAPPINGS ==========
"
" Space as second leader key
nmap <space> <leader>
" save file
nnoremap <leader>w :w<CR>
" jj as easier way to press ESC
inoremap jj <ESC>
" switch highlighting
nnoremap <leader>hl :set hlsearch!<CR>


" ==========  VIMSCRIPT ==========



" ==========  STATUS LINE ==========
"
" Show partial commands on the status line
set showcmd
