" ========== DEFAULT ==========
"
" ===== not grouped =====
" Enable file type plugin
filetype plugin on
" Turn syntax highlighting on.
syntax on
" show line number
set number
" Disable swap files
set noswapfile

" ===== searching =====
" Highlight all search pattern
set hlsearch
" Highlight all matches while entering patter
set incsearch
" Ignore case while searching
set ignorecase
" If at least 1 character Upper case, case-sensitive search
set smartcase

" ===== tabs/spaces =====
" the width of the TAB character
set tabstop=4
" size of indentation
set shiftwidth=4



" ==========  PLUGINS ==========
"
" ===== vim-xkbswitch =====
" Basic configuration
let g:XkbSwitchEnabled=1
" Insert mappings duplicates for Ukrainian layout
let g:XkbSwitchIMappings=['uk']

" ===== netrw =====
" The tree list view in netrw
let g:netrw_liststyle=3
" Remove directory banner
let g:netrw_banner=0
" Open files in new windows
let g:netrw_browse_split=3
" Set the width of the directory explorer
let g:netrw_winsize=10



" ==========  MAPPINGS ==========
"
" Time to print next character in mapping
set timeoutlen=300
" Space as second leader key
nmap <space> <leader>
" save file
nnoremap <leader>w :w<CR>
" switch highlighting
nnoremap <leader>hl :set hlsearch!<CR>


" ==========  VIMSCRIPT ==========



" ==========  STATUS LINE ==========
"
" Show partial commands on the status line
set showcmd



" ========== GVIMRC ==========
"
if has('gui_running')
	" Maximize window
	set lines=100 columns=300
	" DOWNLOAD
	" https://russianfonts.org/fonts/fixedsys-excelsior-301-regular
	" Set default font-size
	set guifont=Fixedsys\ Excelsior\ 3.01\ Regular\ 15
	" Remove the toolbar
	set guioptions-=T
	" Remove scrollbar
	set guioptions-=L
	set guioptions-=r
	" Change default theme
	colorscheme peachpuff
endif
