" ========== DEFAULT ==========
"
" ===== not grouped =====
" Enable file type plugin
filetype plugin on
" Turn syntax highlighting on.
syntax enable
" show line number
set number
" Turn hybrid line numbers on
set number relativenumber
" Disable swap files
set noswapfile
" Disable compatible with Vi
set nocompatible

" ===== windows/splits =====
" Not to change the size of the windows after closing
set noequalalways
" If the split is vertical, a new window appears to the right
setlocal splitright

" ===== searching =====
" Highlight all search pattern
set hlsearch
" Highlight all matches while entering patter
set incsearch
" Ignore case while searching
set ignorecase
" If at least 1 character Upper case, case-sensitive search
set smartcase

" ===== tabs/spaces =====
" the width of the TAB character
set tabstop=4
" size of indentation
set shiftwidth=4
" Insert extra level of indentation in some C-cases
setlocal cindent 
" Backspace erases indentations, end of lines and previously inserted text
set backspace=indent,eol,start



" ========== PLUGINS ==========
"
colorscheme dracula
" Disable default background
highlight Normal ctermbg=NONE



" ========== MAPPINGS ==========
"
" Time to print next character in mapping
set timeoutlen=400
" Space as second leader key
nmap <space> <leader>
" Save file (w = write)
nnoremap <leader>w :w<CR>
" Switch highlighting (hl = highlight)
nnoremap <leader>hl :set hlsearch!<CR>



" ========== VIMSCRIPT ==========



" ========== STATUS LINE ==========
"
" Show partial commands on the status line
set showcmd
