" ========== DEFAULT ==========
"
" ===== not grouped =====
" Enable file type plugin
filetype plugin on
" Turn syntax highlighting on.
syntax on
" show line number
set number
" Turn hybrid line numbers on
set number relativenumber
" Disable swap files
set noswapfile
" Disable compatible with Vi
set nocompatible

" ===== windows/splits =====
" Not to change the size of the windows after closing
set noequalalways
" If the split is vertical, a new window appears to the right
setlocal splitright

" ===== searching =====
" Highlight all search pattern
set hlsearch
" Highlight all matches while entering patter
set incsearch
" Ignore case while searching
set ignorecase
" If at least 1 character Upper case, case-sensitive search
set smartcase

" ===== tabs/spaces =====
" the width of the TAB character
set tabstop=4
" size of indentation
set shiftwidth=4
" Insert extra level of indentation in some C-cases
setlocal cindent 
" Backspace erases indentations, end of lines and previously inserted text
set backspace=indent,eol,start



" ==========  PLUGINS ==========
"
" ===== vim-xkbswitch =====
" Basic configuration
let g:XkbSwitchEnabled=1
" Insert mappings duplicates for Ukrainian layout
let g:XkbSwitchIMappings=['uk']



" ==========  MAPPINGS ==========
"
" Time to print next character in mapping
set timeoutlen=400
" Space as second leader key
nmap <space> <leader>
" Save file (w = write)
nnoremap <leader>w :w<CR>
" Switch highlighting (hl = highlight)
nnoremap <leader>hl :set hlsearch!<CR>
" Open Vim terminal (te = terminal)
nnoremap <leader>te :vertical terminal ++cols=40<CR>



" ==========  VIMSCRIPT ==========
"
" Disable the show of line numbers in Terminal
autocmd TerminalOpen * setlocal nonumber norelativenumber



" ==========  STATUS LINE ==========
"
" Show partial commands on the status line
set showcmd


" ========== GVIMRC ==========
"
if has('gui_running')
	" Maximize window
	set lines=100 columns=300
	" DOWNLOAD
	" https://russianfonts.org/fonts/fixedsys-excelsior-301-regular
	" Set default font-size
	set guifont=Fixedsys\ Excelsior\ 3.01\ Regular\ 15
	" Remove the toolbar
	set guioptions-=T
	" Remove scrollbar
	set guioptions-=L
	set guioptions-=r
endif
